language: go
go:
  - 1.x

before_install:
- nvm install node
- npm install -g yarn @angular/cli
- curl https://glide.sh/get | sh

install:
  - ./loop.sh
  - cd frontend && yarn install && cd ..

script: ./scripts/run-ci.sh
